apiVersion: v1
kind: Service
metadata:
  labels:
    app: dht
  name: dht
  namespace: dht
spec:
  type: LoadBalancer
  ports:
  - name: "server"
    port: 5001
    targetPort: 5001
  selector:
    app: dht