apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-metadata
subjects:
- kind: User
  name: system:anonymous
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: system:serviceaccount:dht:default # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: metadata-reader
  apiGroup: rbac.authorization.k8s.io